@startuml

object Sorgente

object Articolo {
    titolo
    corpo
}

object SerializzatoreDeserializzatore {
    fileSerializzati
}

object AlgoritmoConteggioParole

Sorgente .. Articolo
SerializzatoreDeserializzatore .. Articolo
Articolo .. AlgoritmoConteggioParole

@enduml
