@startuml

left to right direction

Utente --> (Estrazione dei termini)
Deserializzatore <-- (Estrazione dei termini)
Deserializzatore --> (Deserializzazione file xml in articoli)
Contatore <-- (Deserializzazione file xml in articoli)
Contatore --> (Contaggio frequenza termini)
Contatore --> (Salvataggio risultati)

@enduml
